services:
  - type: web
    name: streamx
    env: node
    buildCommand: rm -rf .next && npm install next-pwa tailwindcss postcss autoprefixer && npm install && npm run build
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false # هذا يعني أن المتغير سيتم تعيينه يدويًا في Render
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
    autoDeploy: true # التوزيع التلقائي عند الدفع إلى الفرع الرئيسي 