apiVersion: v1
kind: Service
metadata:
  name: streamx-service
  labels:
    app: streamx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: streamx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - streamx.example.com
    secretName: streamx-tls
  rules:
  - host: streamx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamx-service
            port:
              number: 80 